# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ce9355441c341f3664862eddde09088c1766669d985ab23b02629258c92ee1015955f5a6775222ea029a327de6ea79b2b881c2d4d2039c93a6d53e89b51c00

test:
  secret_key_base: 399d615d103a4d623f72934196f78c0e3a7fa847e167b83b9551f2c8e54804bd64ca7ab9ce64c6d2f0b922e37551869d17b992637959e40af3e52456cb147b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
